# Site settings
title: Bill Martin
email: bill@billmartin.io
url: https://bill-c-martin.github.io
description: "Full-stack web developer that loves building stuff. Musician, Gamer, and general Great Outdoors enthusiast."
skills: "Web Developer"
meta_author: Martin Bill

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1d2120 #80B3FF
  primary-rgb: "29,33,32" #"128,179,255"
  secondary: 5a5c51 #FD6E8A
  secondary-dark: 363730 #A2122F

# Footer settings
footer:
  copyright: Bill Martin
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
 # - title: twitter
 #   url: http://twitter.com/jekyllrb
 # - title: facebook
 #   url:
  - title: stack-overflow
    url: http://stackoverflow.com/users/5743565/bill-martin
 # - title: bitbucket
 #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/bill-c-martin
  - title: linkedin
    url: https://www.linkedin.com/in/billmartin9

# Postal address (add as many lines as necessary)
address:
  - line: 80 Sentinel Court, Apt L00
  - line: Manchester, NH 03103

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
